package actors;

import ecu.se.map.Direction;

public enum Stats {
	ATTACK,
	DEFENSE,
	STRENGTH,
	HEALTH,
	MOVEMENT_SPEED,
	MOVEMENT_DRAG,
	MOVEMENT_ACCELERATION,
	RANGED_WEAPON_ATTACK,
	RANGED_WEAPON_RANGE,
	RANGED_WEAPON_SPEED,
	RANGED_ATTACK_SPEED,
	PROJECTILE_SPEED,
	MELEE_WEAPON_ATTACK,
	MELEE_WEAPON_RANGE,
	MELEE_WEAPON_SPEED,
	MELEE_ATTACK_SPEED,
	MANA_ATTACK,
	MANA_DEFENSE,
	MANA_REGEN,
	HEALTH_REGEN,
	PIERCING_ATTACK,
	PIERCING_DEFENSE,
	BLUNT_ATTACK,
	BLUNT_DEFENSE,
	HELMET_DEFENSE,
	BODY_DEFENSE,
	GAUNTLET_DEFENSE,
	BOOT_DEFENSE,
	XP_GAIN,
	RARITY_CHANCE,
	POISON_RESISTANCE,
	MANA_RESISTANCE,
	RANGED_WEAPON_RESISTANCE,
	MELEE_WEAPON_RESISTANCE,
	FIRE_RESISTANCE,
	COLD_RESISTANCE,
	SHOCK_RESISTANCE;

	Stats() {}
	
	public static void print(float[] stats) {
		for(int i = 0; i < Stats.values().length; i++) {
			System.out.println(Stats.values()[i].name() + ": " + stats[i]);
		}
    }
}


//WEAPON_DECAY_RATE, STAMINA